version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.6.1
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: paranoid_test

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force  # install Hex locally (without prompt)
      - run: mix local.rebar --force  # fetch a copy of rebar (without prompt)

      - run: mix deps.get
      - run: mix test

      - store_test_results:
          path: test-results

